"""add journal entries table

Revision ID: 7c1939cd72c5
Revises: cfe4015d4aa5
Create Date: 2026-08-14 05:32:52.692880

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c1939cd72c5"
down_revision: str | Sequence[str] | None = "cfe4015d4aa5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journal_entries",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("submitted_text", sa.Text(), nullable=False),
        sa.Column("corrected_text", sa.Text(), nullable=False),
        sa.Column("overall_feedback", sa.Text(), nullable=False),
        sa.Column("corrections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "vocabulary_suggestions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_journal_entries_course_id"), "journal_entries", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entries_user_id"), "journal_entries", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_journal_entries_user_id"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_course_id"), table_name="journal_entries")
    op.drop_table("journal_entries")
    # ### end Alembic commands ###
