"""add users.google_sub

Revision ID: 839c4855cdeb
Revises: 68c465c689bd
Create Date: 2026-08-15 14:33:59.646274

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "839c4855cdeb"
down_revision: str | Sequence[str] | None = "68c465c689bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_sub", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_users_google_sub"), "users", ["google_sub"], unique=True)
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected a pre-existing 'ix_cards_due_at'
    # index drop here -- unrelated schema drift from before this migration
    # (superseded by the composite ix_cards_deck_id_due_at, never cleaned
    # up), deliberately left out to keep this migration scoped to auth only.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_google_sub"), table_name="users")
    op.drop_column("users", "google_sub")
    # ### end Alembic commands ###
