"""add reading passages and attempts tables

Revision ID: aa19600096db
Revises: bf7e173bb99c
Create Date: 2026-08-14 12:41:05.425515

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa19600096db"
down_revision: str | Sequence[str] | None = "bf7e173bb99c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate again detected the same pre-existing 'ix_cards_due_at'
    # drift already flagged/excluded in bf7e173bb99c (unrelated to this
    # table) -- deliberately excluded here too, see that migration's note.
    op.create_table(
        "reading_passages",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("target_text", sa.Text(), nullable=False),
        sa.Column("base_text", sa.Text(), nullable=False),
        sa.Column("new_vocabulary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_passages_course_id"), "reading_passages", ["course_id"], unique=False
    )
    op.create_table(
        "reading_passage_attempts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("reading_passage_id", sa.UUID(), nullable=False),
        sa.Column("question_index", sa.Integer(), nullable=False),
        sa.Column("submitted_answer", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("llm_feedback", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["reading_passage_id"], ["reading_passages.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_passage_attempts_reading_passage_id"),
        "reading_passage_attempts",
        ["reading_passage_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_passage_attempts_user_id"),
        "reading_passage_attempts",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reading_passage_attempts_user_id"), table_name="reading_passage_attempts"
    )
    op.drop_index(
        op.f("ix_reading_passage_attempts_reading_passage_id"),
        table_name="reading_passage_attempts",
    )
    op.drop_table("reading_passage_attempts")
    op.drop_index(op.f("ix_reading_passages_course_id"), table_name="reading_passages")
    op.drop_table("reading_passages")
    # ### end Alembic commands ###
