"""add known vocabulary items table

Revision ID: bf7e173bb99c
Revises: 7c1939cd72c5
Create Date: 2026-08-14 11:50:39.741598

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf7e173bb99c"
down_revision: str | Sequence[str] | None = "7c1939cd72c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also detected a pre-existing 'ix_cards_due_at' index
    # drift (present in the live dev DB, absent from the Card model/current
    # migration history -- unrelated to this table) and proposed dropping
    # it here. Deliberately excluded: unrelated to known-vocabulary, and
    # dropping/recreating it belongs in its own migration if/when that
    # drift is actually investigated -- see PLAN.md's Known Issues.
    op.create_table(
        "known_vocabulary_items",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("target_text", sa.String(length=500), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "placement_check",
                "manual",
                "promoted",
                name="knownvocabularysource",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "target_text"),
    )
    op.create_index(
        op.f("ix_known_vocabulary_items_course_id"),
        "known_vocabulary_items",
        ["course_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_known_vocabulary_items_course_id"), table_name="known_vocabulary_items")
    op.drop_table("known_vocabulary_items")
    # ### end Alembic commands ###
